Tenant improvements: IdP identifiers, person fields
contember/engine pull request #295
Opened 2022-07-07 11:35 UTC by matej21

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/contember/engine/295)

2022-07-22 13:13 UTC, JanTvrdik requested changes

2022-07-22 13:32 UTC, JanTvrdik approved these changes
> Reviewed 46 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/295)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)



<!-- Sent from Reviewable.io -->

2022-07-22 13:33 UTC, JanTvrdik requested changes
x

2022-07-25 09:09 UTC, matej21 commented on packages/engine-tenant-api/src/model/service/IDPSignInManager.ts
> +		const saveIdpIdentifier = async (personId: string) =>
This is much more compact, the private method would require 4 arguments.

2022-07-25 09:10 UTC, matej21 commented on packages/engine-tenant-api/src/migrations/2022-07-07-141000-person-display-name.sql
> +SET name = email;
part before `@` is enough, i think

2022-07-25 09:11 UTC, matej21 commented on packages/engine-tenant-api/src/model/service/OtpManager.ts
> +		const otp = await this.otpAuthenticator.create(person.email ?? person.name ?? 'unnamed', label)
email is imho better identifier here

2022-07-25 09:22 UTC, JanTvrdik reviewed
> Reviewed 2 of 42 files at r2, 2 of 11 files at r3, 16 of 22 files at r4, 14 of 16 files at r5, 8 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/295)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)



<!-- Sent from Reviewable.io -->

2022-07-25 09:25 UTC, JanTvrdik commented on packages/engine-tenant-api/src/model/service/IDPSignInManager.ts
> +		const saveIdpIdentifier = async (personId: string) =>
does not matter, you can say that about most private methods. they are used for code structure, not to save bytes

2022-07-25 09:32 UTC, JanTvrdik approved these changes
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/295)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matej21)



<!-- Sent from Reviewable.io -->

2022-07-25 13:09 UTC, merged