CLI: deploy custom frontend, allow deployment without frontend (admin) deploy
contember/engine pull request #456
Opened 2023-07-03 08:18 UTC by sitole

2023-07-03 08:28 UTC, matej21 reviewed
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/456)* status: all files reviewed, 4 unresolved discussions (waiting on @sitole)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPqhOJ9eKMZFeuc-8j):*
there is also a tenant part in this commit, please split it
___
*[`packages/cli/src/commands/deploy/DeployCommand.ts` line 45 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPrHGOEFy2ykWatWcG:-NZPrHGOEFy2ykWatWcH:b-mmkgff) ([raw file](https://github.com/contember/engine/blob/a8aabd214fbe7f654388381f2785bf90979f4b8d/packages/cli/src/commands/deploy/DeployCommand.ts#L45)):*
> ```XML
> 
> 		configuration.option('admin').valueRequired()
> 		configuration.option('no-admin').valueOptional()
> ```

both no-admin and root should be `valueNone`
___
*[`packages/cli/src/commands/deploy/DeployCommand.ts` line 129 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPqoiX4t-pSjXpAgEb:-NZPqoiX4t-pSjXpAgEc:b-11vofc) ([raw file](https://github.com/contember/engine/blob/a8aabd214fbe7f654388381f2785bf90979f4b8d/packages/cli/src/commands/deploy/DeployCommand.ts#L129)):*
> ```XML
> 		}
> 
> 		if (adminEndpoint && input.getOption('no-admin') != true) {
> ```

`!== true`
___
*[`packages/engine-tenant-api/src/model/authorization/PermissionsFactory.ts` line 54 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPr-127i52T8Ol2ggh:-NZPr-127i52T8Ol2ggi:b-2n4i8r) ([raw file](https://github.com/contember/engine/blob/a8aabd214fbe7f654388381f2785bf90979f4b8d/packages/engine-tenant-api/src/model/authorization/PermissionsFactory.ts#L54)):*
> ```XML
> 
> 		permissions.allow(TenantRole.PROJECT_CREATOR, PermissionActions.PROJECT_CREATE)
> 		permissions.allow(TenantRole.PROJECT_CREATOR, PermissionActions.ENTRYPOINT_DEPLOY)
> ```

we need a new role for this. project_creator is an internal role in cloud, a user cannot obtain it. So create a sth like `ENTRYPOINT_DEPLOYER` and add it to `allowedRoles` list


<!-- Sent from Reviewable.io -->

2023-07-04 10:52 UTC, sitole reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/engine/456)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @matej21 and @sitole)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPqhOJ9eKMZFeuc-8j):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

there is also a tenant part in this commit, please split it
</blockquote></details>

Done.
___
*[`packages/cli/src/commands/deploy/DeployCommand.ts` line 45 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPrHGOEFy2ykWatWcG:-NZVTidLAkaghm7hk2qa:b-896fix) ([raw file](https://github.com/contember/engine/blob/a8aabd214fbe7f654388381f2785bf90979f4b8d/packages/cli/src/commands/deploy/DeployCommand.ts#L45)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

both no-admin and root should be `valueNone`
</blockquote></details>

Done.
___
*[`packages/cli/src/commands/deploy/DeployCommand.ts` line 129 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPqoiX4t-pSjXpAgEb:-NZVTohh5nnzS56P5O1V:b-896fix) ([raw file](https://github.com/contember/engine/blob/a8aabd214fbe7f654388381f2785bf90979f4b8d/packages/cli/src/commands/deploy/DeployCommand.ts#L129)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

`!== true`
</blockquote></details>

Done.
___
*[`packages/engine-tenant-api/src/model/authorization/PermissionsFactory.ts` line 54 at r1](https://reviewable.io/reviews/contember/engine/456#-NZPr-127i52T8Ol2ggh:-NZVX0Ry6S15gJbCfa9J:b-896fix) ([raw file](https://github.com/contember/engine/blob/a8aabd214fbe7f654388381f2785bf90979f4b8d/packages/engine-tenant-api/src/model/authorization/PermissionsFactory.ts#L54)):*
<details><summary><i>Previously, matej21 (David Matějka) wrote…</i></summary><blockquote>

we need a new role for this. project_creator is an internal role in cloud, a user cannot obtain it. So create a sth like `ENTRYPOINT_DEPLOYER` and add it to `allowedRoles` list
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-04 11:52 UTC, sitole commented
todo: add `-no-migrations` ability to disable database migrations (useful with new custom app deployment)

2023-07-04 13:22 UTC, matej21 reviewed
> Reviewed 1 of 3 files at r2, 4 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/456)* status: all files reviewed, 2 unresolved discussions (waiting on @sitole)

___
*[`-- commits` line 10 at r4](https://reviewable.io/reviews/contember/engine/456#-NZW2oZJ1h68tmwY71_P):*
it is a "feat", not "chore"
___
*[`packages/cli/src/commands/deploy/DeployCommand.ts` line 83 at r1](https://reviewable.io/reviews/contember/engine/456#-NZW2znABbdZJzCRfhqs:-NZW2znABbdZJzCRfhqt:b309qpo) ([raw file](https://github.com/contember/engine/blob/a8aabd214fbe7f654388381f2785bf90979f4b8d/packages/cli/src/commands/deploy/DeployCommand.ts#L83)):*
> ```XML
> 
> 		const projectAdminDistDir = `${project.adminDir}/dist`
> 		if (adminEndpoint && !(await pathExists(`${projectAdminDistDir}/index.html`))) {
> ```

we should probably keep the IF here, just also add `no-admin` check. so if you want to deploy the admin (not passing --no-admin) and dist file does not exist, it should fail early.


<!-- Sent from Reviewable.io -->

2023-07-04 14:26 UTC, matej21 reviewed
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sitole)



<!-- Sent from Reviewable.io -->

2023-07-10 11:09 UTC, matej21 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/engine/456)* status: all files reviewed, 2 unresolved discussions (waiting on @sitole)

___
*[`-- commits` line 7 at r6](https://reviewable.io/reviews/contember/engine/456#-NZzTha45HyLdGS48n4b):*
commit  message notes:

chore => style
tenant => tenant-api
___
*[`packages/cli/src/commands/deploy/DeployCommand.ts` line 146 at r6](https://reviewable.io/reviews/contember/engine/456#-NZzU4lJ8oJk1QrXyj4p:-NZzU4lJ8oJk1QrXyj4q:b-1m9fqb) ([raw file](https://github.com/contember/engine/blob/9aef2d02ba249bf9f1467d22a2742d0c1020cc25/packages/cli/src/commands/deploy/DeployCommand.ts#L146)):*
> ```XML
> 			// with root option you can build app on your own and simply deploy it with subprojects
> 			await client.deploy(
> 				input.getOption('root') ? null : remoteProject, files,
> ```

pls reformat:
- either single line (and extract "deployedProject" variable)
- or push "files" arg to next line


<!-- Sent from Reviewable.io -->

2023-08-16 14:05 UTC, merged